### PR TITLE
:bug: Fixes #32 - Use ByteArrayOutputStream

### LINKED ISSUE #32: ClassNotFoundException: com.sun.xml.internal.messaging.saaj.util.ByteOutputStream
Exception while publishing a plugin

```
Caused by: java.lang.NoClassDefFoundError: com/sun/xml/internal/messaging/saaj/util/ByteOutputStream
        at org.jetbrains.intellij.pluginRepository.CompositeConverter.fromBody(pluginRepositoryRest.kt:93)
        at retrofit.RetrofitError.getBodyAs(RetrofitError.java:137)
        at retrofit.RetrofitError.getBody(RetrofitError.java:112)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.retrofitErrorMessage(pluginRepositoryRest.kt:219)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.processRetofitError(pluginRepositoryRest.kt:202)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPluginInternal(pluginRepositoryRest.kt:167)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPluginInternal$default(pluginRepositoryRest.kt:153)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt:138)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin$default(pluginRepositoryRest.kt:137)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance.uploadPlugin(pluginRepositoryRest.kt)
        at org.jetbrains.intellij.pluginRepository.PluginRepositoryInstance$uploadPlugin.call(Unknown Source)
        at org.jetbrains.intellij.tasks.PublishTask.publishPlugin(PublishTask.groovy:130)
```

This appears to have been introduced in https://github.com/JetBrains/plugin-repository-rest-client/commit/c132ac89713a134edcb37f706c1200e008b3d99d. I think this is an import mistake: I assume`import com.sun.xml.internal.messaging.saaj.util.ByteOutputStream` should be `import java.io. ByteArrayOutputStream`

### PR DESCRIPTION
**Pull request by gilday**
The class `com.sun.xml.internal.messaging.saaj.util.ByteOutputStream` cannot be found on all Java releases because it is an internal class.

### CODE REVIEW

**Comment by zolotov** [comment]
thanks!
